###

 Get http://127.0.0.1:8081/api/v1/info
 Content-Type: application/json

###

 Get http://127.0.0.1:8081/api/v1/health
 Content-Type: application/json


####
Get http://127.0.0.1:8081/api/v1/ws
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2OTI2MGJkNC0xZDcwLTQ1YjQtOWNjMi0yZjNkNzZhNmU1YTciLCJuYW1lIjoiU2FkZWdoIiwiZW1haWwiOiIxMDMyNDk1NzU1NDg2NTg1MjA1ODkiLCJpYXQiOjE2OTAxMDA3MjMsImV4cCI6MTY5MDk2NTMyM30.H25kcvY3POn1pinCAk60617YtbX8ja_gMQwcQgA9ZHY
